### ISSUE TITLE
turms-service cant connect to turms-gateway

### ISSUE THREAD

**Issue by LinkZhang** [turms-im/turms#910]
turms-gateway started and healthy, but get some errors from turms-service log
![image](https://user-images.githubusercontent.com/10371414/148710378-c3fe7a34-b35d-47aa-9661-e92c5e8b9dee.png)

```
2022-01-10 01:54:12.946  INFO S sdefmdhv                     main im.turms.service.TurmsServiceApplication : Started TurmsServiceApplication in 9.656 seconds (JVM running for 11.58)
2022-01-10 01:54:15.020  INFO S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : The current online users number is: 0
2022-01-10 01:54:20.848  INFO S sdefmdhv                     turms-mongo-event-loop-24-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:32, serverValue:67}] to mongodb-router:27017
2022-01-10 01:54:29.966  INFO S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : The current online users number is: 0
2022-01-10 01:54:30.866  INFO S sdefmdhv                     turms-mongo-watch-1          i.t.s.c.c.s.c.ConnectionService : [Client] Connecting to member: jbuosmdv[turms-gateway:7610]. Retry times: 0
2022-01-10 01:54:30.931  INFO S sdefmdhv                     turms-cluster-connection-client-io-19-1          i.t.s.c.c.s.c.ConnectionService : [Client] Connected to member: jbuosmdv[turms-gateway:7610]
2022-01-10 01:54:30.950  INFO S sdefmdhv                     turms-cluster-connection-client-io-19-1          i.t.s.c.c.s.c.ConnectionService : [Client] Sending a open handshake request to member: jbuosmdv[turms-gateway:7610]
2022-01-10 01:54:31.055  INFO S sdefmdhv                     turms-cluster-connection-client-io-19-1          i.t.s.c.c.s.c.ConnectionService : [Client] Completed the handshake with member: jbuosmdv[turms-gateway:7610]
2022-01-10 01:54:45.007  INFO S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : The current online users number is: 0
2022-01-10 01:54:46.556  WARN S sdefmdhv                     turms-cluster-connection-keepalive-21-1          i.t.s.c.c.s.c.ConnectionService : Reconnecting to the member jbuosmdv due to keepalive timeout
2022-01-10 01:54:59.969 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:55:15.001 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:55:29.966 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
root@efe0c69df147:/opt/turms/turms-service# tail -f turms-service_20220110_0.log 
2022-01-10 01:54:59.969 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:55:15.001 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:55:29.966 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:55:45.001 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:55:59.966 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established
2022-01-10 01:56:15.001 ERROR S sdefmdhv                     pool-7-thread-1          i.t.s.w.s.i.s.StatisticsService : Failed to count online users
im.turms.server.common.cluster.service.rpc.exception.RpcException: 4:1201:Not all connections are established

```

**Comment by JamesChenX** [comment]
The bug should have been fixed and you can pull the images again via `docker pull ghcr.io/turms-im/turms-gateway:latest && docker pull ghcr.io/turms-im/turms-service:latest`, and rerun `docker-compose.standalone.yml`

**Comment by LinkZhang** [comment]
![image](https://user-images.githubusercontent.com/10371414/148735457-9c2d7f3f-176e-448e-b581-bd3d09305abc.png)
I think in the ConnectService class it needs to be fixed too

**Comment by JamesChenX** [comment]
@LinkZhang The code you paste is fine because `rpcService.requestResponse` will never return `MonoEmpty`(`Mono.empty()`).
But your suggestion is good and I will update the code for better maintainability when I commit a PR for other things on the server side. Thanks.

**Comment by LinkZhang** [comment]
this is the origin code
![image](https://user-images.githubusercontent.com/10371414/148739907-e4dd315f-75ee-4d5e-89a2-6c057ee5a315.png)

![image](https://user-images.githubusercontent.com/10371414/148739172-5e9522e1-6e51-4740-8e87-8c23bfa215ea.png)
if didn't fix it, cant update the last keeplive timestamp so gateway will keep reconnecting, when fixed the code like which I pasted above,it works.

**Comment by JamesChenX** [comment]
@LinkZhang Thanks, I made a mistake and it will return `MonoEmpty` and not call the `consumer` in the subscribe as I commented in the code, hhh. I will update it later. Thanks.
![image](https://user-images.githubusercontent.com/44962329/148740394-408356b4-945d-4ff8-a3fc-1735a1ca23ba.png)

**Comment by JamesChenX** [comment]
@LinkZhang I have published and verified the latest image that should have fixed the bug.
So I close this ticket, please feel free to reopen it if you encounter any problems.
